export const players = [{
    name: "Arregui",
    alt: "Arregui", 
    src: "/ferro/arregui.png"
}, {
    name: "Gómez",
    alt: "Gómez",
    src: "/ferro/gomez.png"
}, {
    name: "Garré",
    alt: "Garré",
    src: "/ferro/garre.png"
}, {
    name: "Cúper",
    alt: "Cúper",
    src: "/ferro/cuper.png"
}, {
    name: "Rocchia",
    alt: "Rocchia",
    src: "/ferro/rocchia.png"
}, {
    name: "Basigalup",
    alt: "Basigalup",
    src: "/ferro/basigalup.png"
}, {
    name: "Saccardi",
    alt: "Saccardi",
    src: "/ferro/saccardi.png"
}, {
    name: "Júarez",
    alt: "Júarez",
    src: "/ferro/juarez.png"
}, {
    name: "Cañete",
    alt: "Cañete",
    src: "/ferro/cañete.png"
}, {
    name: "Márcico",
    alt: "Márcico",
    src: "/ferro/marcico.png"
}, {
    name: "Crocco",
    alt: "Crocco",
    src: "/ferro/crocco.png"
}, {
    name: "Griguol",
    alt: "Griguol",
    src: "/ferro/griguol.png"
}
]